export const permissions = [
    // INVENTORY
    "VIEW_INVENTORY",
    "MANAGE_PRODUCTS",
    "ADJUST_STOCK",
    "RECEIVE_STOCK",
    "VIEW_INVENTORY_REPORTS",

    // SALES
    "PROCESS_SALES",
    "PROCESS_PAYMENTS",
    "VOID_SALE",
    "PROCESS_REFUNDS",
    "VIEW_SALES_HISTORY",
    "VIEW_SALES_REPORTS",

    // UTANG
    "CREATE_UTANG",
    "PROCESS_UTANG_PAYMENT",
    "SET_CUSTOMER_CREDIT_LIMIT",
    "SET_STORE_CREDIT_POLICY",
    "MANAGE_OVERDUE_ACCOUNTS",
    "VIEW_UTANG_REPORTS",
    "WRITE_OFF_BAD_DEBT",

    // CUSTOMER
    "VIEW_CUSTOMERS",
    "MANAGE_CUSTOMERS",
    "DELETE_CUSTOMERS",

    // REPORTS
    "VIEW_DAILY_SUMMARY",
    "VIEW_FINANCIAL_REPORTS",
    "MANAGE_EXPENSES",
    "CLOSE_DAILY_REGISTER",

    // USER
    "MANAGE_USERS",
    "VIEW_USER_ACTIVITY",
    "CHANGE_OWN_PASSWORD",
    "RESET_USER_PASSWORD",

    //  SYSTEM
    "CONFIGURE_STORE_SETTINGS",
    "BACKUP_DATA",
    "RESTORE_DATA",
    "MANAGE_SYSTEM_SETTINGS"
];