-- Generated by the database client.
CREATE TABLE account_roles(
    account_id integer NOT NULL,
    role_id integer NOT NULL,
    PRIMARY KEY(account_id,role_id),
    CONSTRAINT account_roles_account_id_fkey FOREIGN key(account_id) REFERENCES accounts(id),
    CONSTRAINT account_roles_role_id_fkey FOREIGN key(role_id) REFERENCES roles(id)
);

-- Generated by the database client.
CREATE TABLE accounts(
    id SERIAL NOT NULL,
    profile_id integer NOT NULL,
    employee_id uuid NOT NULL,
    password_hash varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT accounts_profile_id_fkey FOREIGN key(profile_id) REFERENCES profiles(id)
);
CREATE UNIQUE INDEX accounts_employee_id_key ON public.accounts USING btree (employee_id);

-- Generated by the database client.
CREATE TABLE customers(
    id SERIAL NOT NULL,
    profile_id integer NOT NULL,
    utang_limit numeric(10,2) NOT NULL DEFAULT 0,
    total_utang numeric(10,2) NOT NULL DEFAULT 0,
    current_balance numeric(10,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT customers_profile_id_fkey FOREIGN key(profile_id) REFERENCES profiles(id)
);
COMMENT ON COLUMN customers.current_balance IS 'Current balance of the customer (after utang payments)';

-- Generated by the database client.
CREATE TABLE inventories(
    id SERIAL NOT NULL,
    product_id integer NOT NULL,
    updated_by integer NOT NULL,
    quantity integer NOT NULL,
    cost_price numeric(10,2) NOT NULL,
    minimum_stock integer NOT NULL,
    expiry_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT inventories_product_id_fkey FOREIGN key(product_id) REFERENCES products(id),
    CONSTRAINT inventories_updated_by_fkey FOREIGN key(updated_by) REFERENCES accounts(id)
);

-- Generated by the database client.
CREATE TABLE permissions(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX permissions_name_key ON public.permissions USING btree (name);

-- Generated by the database client.
CREATE TABLE product_categories(
    id SERIAL NOT NULL,
    category_id integer,
    name varchar(255) NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE products(
    id SERIAL NOT NULL,
    category_id integer NOT NULL,
    name varchar(255) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    unit_type varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT products_category_id_fkey FOREIGN key(category_id) REFERENCES product_categories(id)
);

-- Generated by the database client.
CREATE TABLE profiles(
    id SERIAL NOT NULL,
    first_name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    middle_name varchar(255),
    suffix varchar(255),
    birth_date timestamp with time zone NOT NULL,
    phone_number varchar(255) NOT NULL,
    address varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE role_permissions(
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    PRIMARY KEY(role_id,permission_id),
    CONSTRAINT role_permissions_role_id_fkey FOREIGN key(role_id) REFERENCES roles(id),
    CONSTRAINT role_permissions_permission_id_fkey FOREIGN key(permission_id) REFERENCES permissions(id)
);

-- Generated by the database client.
CREATE TABLE roles(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX roles_name_key ON public.roles USING btree (name);

-- Generated by the database client.
CREATE TABLE sale_items(
    id SERIAL NOT NULL,
    sale_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    total numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT sale_items_sale_id_fkey FOREIGN key(sale_id) REFERENCES sales(id),
    CONSTRAINT sale_items_product_id_fkey FOREIGN key(product_id) REFERENCES products(id)
);

-- Generated by the database client.
CREATE TABLE sales(
    id SERIAL NOT NULL,
    processed_by integer NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    payment_method enum_sales_payment_method NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT sales_processed_by_fkey FOREIGN key(processed_by) REFERENCES accounts(id)
);

-- Generated by the database client.
CREATE TABLE utang_payments(
    id SERIAL NOT NULL,
    utang_id integer NOT NULL,
    processed_by integer NOT NULL,
    amount_paid numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT utang_payments_utang_id_fkey FOREIGN key(utang_id) REFERENCES utangs(id),
    CONSTRAINT utang_payments_processed_by_fkey FOREIGN key(processed_by) REFERENCES accounts(id)
);

-- Generated by the database client.
CREATE TABLE utangs(
    id SERIAL NOT NULL,
    customer_id integer NOT NULL,
    sale_id integer,
    total_amount numeric(10,2) NOT NULL DEFAULT 0,
    remaining_balance numeric(10,2) NOT NULL DEFAULT 0,
    payment_status enum_utangs_payment_status NOT NULL DEFAULT 'unpaid'::enum_utangs_payment_status,
    due_date timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT utangs_customer_id_fkey FOREIGN key(customer_id) REFERENCES customers(id),
    CONSTRAINT utangs_sale_id_fkey FOREIGN key(sale_id) REFERENCES sales(id)
);